version: '3.8'

services:

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    networks:
      - produto_net
    environment:
      MONGO_INITDB_DATABASE: mongodb
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    volumes:
      - mongo_vol:/data/db
    

  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8081:8081
    networks:
      - produto_net
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: mongouser
      ME_CONFIG_MONGODB_AUTH_PASSWORD: mongopwd
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopwd@localhost:27017/db?ssl=false
volumes:
  mongo_vol: 
networks:
  produto_net:
   