version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports: 
     - 6379:6379
    networks: 
      - redis_net
    volumes:
      - redis_vol:/data/db
    

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: commander 
    restart: always
    ports: 
      - 8081:8081
    networks: 
      - redis_net
    volumes:
      - redis_vol:/data/db
    environment:
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin 
networks:
  redis_net:
volumes:
   redis_vol: